### ISSUE TITLE
Automatically add `flag_key` as `targeting_key`

### ISSUE THREAD

**Issue by maxveldink** [launchdarkly/openfeature-ruby-server#13]
**Is your feature request related to a problem? Please describe.**
We recently switched from our internal LD OF provider to this one (thank you 🙏🏻 ). One thing we were doing internally to aid with usability was automatically setting the LD targeting key to the passed in flag key, if it was not already present. This makes for much cleaner call sites, especially since we're wanting to hide the fact we're using LD under the hood to our users (developers).

**Describe the solution you'd like**
When there's a call like `client.fetch_boolean_value(flag_key: "testing", default_value: true)` on the OF side, instead of returning a `MISSING_TARGETING_KEY` error with default, we create an eval context in the provider, set the targeting key to the flag key and pass that through.

If an eval context is provided, *without* a targeting key set, we do the same behavior.

**Describe alternatives you've considered**
We are able to make this work with some helper code implemented internally, but would love to see it upstream.

**Additional context**
As a contributor to the Ruby SDK, happy to help with implementation of this/any issues you all run into with using the OF Ruby SDK 🙏🏻 I can put up a PR soon with a sample implementation, if this is something the project is interested in.

**Comment by keelerm84** [comment]
Good afternoon 👋🏼 and glad to hear you were able to switch over to this SDK.

> One thing we were doing internally to aid with usability was automatically setting the LD targeting key to the passed in flag key, if it was not already present. 

The targeting key (context key in LaunchDarkly parlance) is a different concept from the flag key. While it may work for your particular use case, as a general feature of the LD SDK, I don't think it makes sense.

As you're likely aware, the OpenFeature spec calls for [hook support](https://openfeature.dev/specification/sections/hooks/). I believe this feature would allow you to accomplish the same thing without requiring modifications to this (or any provider's) SDK.

Unfortunately, the OpenFeature Ruby SDK [doesn't currently support hooks](https://github.com/open-feature/ruby-sdk/issues/52). Once official support is added, we can update our provider (happy to accept a PR then).

**Comment by maxveldink** [comment]
Got it, that makes sense. I've currently got adding hook support prioritized so I'll try and get that added soon. Thanks!
